// vue-chat-app/src/components/Chat.vue
<template>
  <div class="chat">
    <div class="chat__header">
      <span class="chat__title">Test</span>
    </div>
    <div class="chat__messages">
      <div v-for="message in messages" :key="message.timestamp" class="message">
        <span class="message__author">{{ message.author }}</span>
        <span class="message__timestamp">{{ message.timestamp }}</span>
        <div class="message__text">{{ message.text }}</div>
      </div>
    </div>
    <div class="chat__new-message">
      <input type="text" placeholder="Type here..." class="chat__input" v-model="newMessage" />
      <button class="chat__button" @click="sendMessage">Send</button>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      newMessage: '',
      messages: [
        {
          author: 'Julius Caesar',
          timestamp: '12:44 pm',
          text: 'Thank you for contacting our online support center. How may I assist you today?'
        }
      ]
    };
  },
  methods: {
    sendMessage() {
      if (this.newMessage.trim() !== '') {
        this.messages.push({
          author: 'Current User',
          timestamp: new Date().toLocaleTimeString(),
          text: this.newMessage
        });
        this.newMessage = '';
      }
    }
  }
};
</script>

<style scoped>
.chat {
  display: flex;
  flex-direction: column;
  height: 100vh;
  border: 1px solid #ccc;
}
.chat__header {
  background-color: #349BB1;
  padding: 10px;
}
.chat__title {
  color: white;
}
.chat__messages {
  flex: 1 1 auto;
}
.chat__new-message {
  display: flex;
  padding: 10px;
}
.chat__input {
  flex-grow: 1;
  margin-right: 10px;
}
.chat__button {
  background-color: #349BB1;
  color: white;
  border: none;
  padding: 10px 20px;
  cursor: pointer;
}
.chat__button:hover {
  background-color: #C1EEF7;
}
.message {
  padding: 10px;
}
.message__author {
  font-weight: bold;
}
.message__timestamp {
  float: right;
  opacity: 0.6;
}
.message__text {
  display: block;
  clear: both;
}
</style>

// react-chat-app/src/components/chat/Chat.tsx
import React, { useState } from 'react';
import './Chat.scss';

const Chat: React.FC = () => {
    const [newMessage, setNewMessage] = useState('');
    const [messages, setMessages] = useState([
        {
            author: 'Julius Caesar',
            timestamp: '12:44 pm',
            text: 'Thank you for contacting our online support center. How may I assist you today?'
        }
    ]);

    const sendMessage = () => {
        if (newMessage.trim() !== '') {
            const message = {
                author: 'Current User',
                timestamp: new Date().toLocaleTimeString(),
                text: newMessage
            };
            setMessages([...messages, message]);
            setNewMessage('');
        }
    };

    return (
        <div className="chat">
            <div className="chat__header">
                <span className="chat__title">Test</span>
            </div>
            <div className="chat__messages">
                {messages.map((message, index) => (
                    <div key={index} className="message">
                        <span className="message__author">{message.author}</span>
                        <span className="message__timestamp">{message.timestamp}</span>
                        <span className="message__text">{message.text}</span>
                    </div>
                ))}
            </div>
            <div className="chat__new-message">
                <input
                    type="text"
                    value={newMessage}
                    onChange={(e) => setNewMessage(e.target.value)}
                    placeholder="Type a message..."
                    className="chat__input"
                />
                <button onClick={sendMessage} className="chat__button">Send</button>
            </div>
        </div>
    );
};

export default Chat;
