// react/src/App.tsx
import React, { useState, useEffect } from 'react';
import StartChatForm from './components/start-chat-form/StartChatForm';
import Chat from './components/chat/Chat';

const PARENT_ORIGIN = 'http://localhost:63342';

enum Step {
  StartChatForm = 'StartChatForm',
  Chat = 'Chat'
}

const App: React.FC = () => {
    const [step, setStep] = useState(Step.StartChatForm);

    useEffect(() => {
        const onMessage = (event: MessageEvent) => {
            if (event.origin !== PARENT_ORIGIN) {
                return;
            }

            if (event.data) {
                applyCustomStyles(event.data);
            }
        };

        window.addEventListener('message', onMessage);
        return () => window.removeEventListener('message', onMessage);
    }, []);

    const applyCustomStyles = (styles: Record<string, string>) => {
        Object.keys(styles).forEach(key => {
            document.documentElement.style.setProperty(key, styles[key]);
        });
    };

    return (
        <div>
            {step === Step.StartChatForm && <StartChatForm onSubmit={() => setStep(Step.Chat)} />}
            {step === Step.Chat && <Chat />}
        </div>
    );
};

export default App;

// angular/src/app/app.component.ts
import {Component, HostListener} from '@angular/core';
import {StartChatFormComponent} from "./components/start-chat-form/start-chat-form.component";
import {ChatComponent} from "./components/chat/chat.component";
import {NgSwitch, NgSwitchCase} from "@angular/common";

const PARENT_ORIGIN = 'http://localhost:63342';

enum Step {
  StartChatForm = 'StartChatForm',
  Chat = 'Chat'
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  standalone: true,
  imports: [StartChatFormComponent, ChatComponent, NgSwitch, NgSwitchCase]
})
export class AppComponent {
    @HostListener('window:message', ['$event']) public onMessage(event: MessageEvent) {
        if (event.origin !== PARENT_ORIGIN) {
            return;
        }

        if (event.data) {
            this._applyCustomStyles(event.data);
        }
    }

    public Step = Step;

    public step: Step = Step.StartChatForm;

    public startChat() {
        this.step = Step.Chat;
    }

    private _applyCustomStyles(styles: Record<string, string>) {
        Object.keys(styles).forEach((key) => {
            document.documentElement.style.setProperty(key, styles[key]);
        });
    }
}

<ng-container [ngSwitch]="step">
  <app-start-chat-form
    *ngSwitchCase="Step.StartChatForm"
    (submitted)="startChat()"
  ></app-start-chat-form>
  <app-chat
    *ngSwitchCase="Step.Chat"
  ></app-chat>
</ng-container>
