// angular-chat-app/src/app/components/start-chat-form/start-chat-form.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {FormControl, FormGroup, ReactiveFormsModule, Validators} from "@angular/forms";
import {of} from "rxjs";

@Component({
  selector: 'app-start-chat-form',
  templateUrl: './start-chat-form.component.html',
  styleUrls: ['./start-chat-form.component.scss'],
  standalone: true,
  imports: [ReactiveFormsModule]
})
export class StartChatFormComponent implements OnInit {
  @Output() public submitted: EventEmitter<boolean> = new EventEmitter<boolean>();

  public chatForm!: FormGroup;

  public ngOnInit() {
    this.chatForm = new FormGroup({
      name: new FormControl(null, Validators.required),
      email: new FormControl(null, [Validators.required, Validators.email]),
      question: new FormControl(null, Validators.required)
    });
  }

  public submit() {
    if (this.chatForm.valid) {
      of([]).subscribe(() => {
        this.submitted.emit(true);
      });
    }
  }
}

<div class="chat">
    <div class="chat__body">
      <div class="chat__form">
        <input type="text" placeholder="Name" />
        <input type="email" placeholder="Email" />
        <textarea placeholder="Question"></textarea>
      </div>
      <button class="chat__start-btn">Start chat</button>
    </div>
</div>

// react-chat-app/src/components/start-chat-form/StartChatForm.tsx
import React, {useState} from 'react';
import './StartChatForm.scss';

interface StartChatFormProps {
    onSubmit: () => void;
}

const StartChatForm: React.FC<StartChatFormProps> = ({ onSubmit }) => {
    const [formData, setFormData] = useState({
        name: '',
        email: '',
        question: ''
    });

    const isValidForm = () => {
        return formData.name && formData.email.includes('@') && formData.question;
    };

    const handleSubmit = (event: React.FormEvent) => {
        event.preventDefault();

        if (isValidForm()) {
            onSubmit();
        }
    };

    const handleChange = (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
        setFormData({ ...formData, [event.target.name]: event.target.value });
    };

    return (
        <div className="chat">
            <form onSubmit={handleSubmit} className="chat__body">
                <div className="chat__form">
                    <input
                        type="text"
                        name="name"
                        value={formData.name}
                        onChange={handleChange}
                        placeholder="Name"
                        required
                    />
                    <input
                        type="email"
                        name="email"
                        value={formData.email}
                        onChange={handleChange}
                        placeholder="Email"
                        required
                    />
                    <textarea
                        name="question"
                        value={formData.question}
                        onChange={handleChange}
                        placeholder="Your Question"
                        required
                    />
                </div>
                <button type="submit" className="chat__start-btn">Start Chat</button>
            </form>
        </div>
    );
};

export default StartChatForm;
