// angular/src/app/components/chat/chat.component.ts
import { Component } from '@angular/core';
import {FormsModule} from "@angular/forms";
import {NgFor} from "@angular/common";

interface IMessage {
  author: string;
  timestamp: string;
  text: string;
}

@Component({
  selector: 'app-chat',
  templateUrl: './chat.component.html',
  styleUrls: ['./chat.component.scss'],
  standalone: true,
  imports: [FormsModule, NgFor]
})
export class ChatComponent {
    public newMessage: string = '';

    public messages: IMessage[] = [
        {
            author: 'Julius Caesar',
            timestamp: '12:44 pm',
            text: 'Thank you for contacting our online support center. How may I assist you today?'
        }
    ];

    public sendMessage() {
        if (this.newMessage.trim() !== '') {
            this.messages.push({
                author: 'Current User',
                timestamp: new Date().toLocaleTimeString(),
                text: this.newMessage
            });

            this.newMessage = '';
        }
    }
}

<div class="chat">
    <h1 class="chat__header">Angular Test Chat</h1>
    <div class="chat__messages">
        <div *ngFor="let message of messages" class="message">
            <div class="message__header">
              <span class="message__author">{{message.author}}</span>
              <span class="message__timestamp">{{message.timestamp}}</span>
            </div>
            <div class="message__text">{{message.text}}</div>
        </div>
    </div>
    <div class="chat__new-message new-message">
        <input type="text" placeholder="Type here..." class="new-message__input" [(ngModel)]="newMessage" />
        <button class="new-message__btn" (click)="sendMessage()">Send</button>
    </div>
</div>

// react/src/components/chat/Chat.tsx
import React, { useState } from 'react';
import './Chat.scss';

const Chat: React.FC = () => {
    const [newMessage, setNewMessage] = useState('');
    const [messages, setMessages] = useState([
        {
            author: 'Julius Caesar',
            timestamp: '12:44 pm',
            text: 'Thank you for contacting our online support center. How may I assist you today?'
        }
    ]);

    const sendMessage = () => {
        if (newMessage.trim() !== '') {
            const message = {
                author: 'Current User',
                timestamp: new Date().toLocaleTimeString(),
                text: newMessage
            };
            setMessages([...messages, message]);
            setNewMessage('');
        }
    };

    return (
        <div className="chat">
            <h1 className="chat__header">React Test Chat</h1>
            <div className="chat__messages">
                {messages.map((message, index) => (
                    <div key={index} className="message">
                        <div className="message__header">
                            <span className="message__author">{message.author}</span>
                            <span className="message__timestamp">{message.timestamp}</span>
                        </div>
                        <div className="message__text">{message.text}</div>
                    </div>
                ))}
            </div>
            <div className="chat__new-message new-message">
                <input
                    type="text"
                    value={newMessage}
                    onChange={(e) => setNewMessage(e.target.value)}
                    placeholder="Type a message..."
                    className="new-message__input"
                />
                <button onClick={sendMessage} className="new-message__btn">Send</button>
            </div>
        </div>
    );
};

export default Chat;
