// react/src/components/start-chat-form/StartChatForm.tsx
import React, {useState} from 'react';
import './StartChatForm.scss';

interface StartChatFormProps {
    onSubmit: () => void;
}

const StartChatForm: React.FC<StartChatFormProps> = ({ onSubmit }) => {
    const [formData, setFormData] = useState({
        name: '',
        email: '',
        question: ''
    });

    const isValidForm = () => {
        return formData.name && formData.email.includes('@') && formData.question;
    };

    const handleSubmit = (event: React.FormEvent) => {
        event.preventDefault();

        if (isValidForm()) {
            onSubmit();
        }
    };

    const handleChange = (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
        setFormData({ ...formData, [event.target.name]: event.target.value });
    };

    return (
        <form onSubmit={handleSubmit} className="start-chat">
            <div className="start-chat__body">
                <input
                    type="text"
                    name="name"
                    value={formData.name}
                    onChange={handleChange}
                    placeholder="Name"
                    className='start-chat__input'
                    required
                />
                <input
                    type="email"
                    name="email"
                    value={formData.email}
                    onChange={handleChange}
                    placeholder="Email"
                    className='start-chat__input'
                    required
                />
                <textarea
                    name="question"
                    value={formData.question}
                    onChange={handleChange}
                    placeholder="Your Question"
                    className='start-chat__textarea'
                    required
                />
            </div>
            <button type="submit" className='start-chat__btn' disabled={!isValidForm()}>Start React Chat</button>
        </form>
    );
};

export default StartChatForm;

// angular/src/app/components/start-chat-form/start-chat-form.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {FormControl, FormGroup, ReactiveFormsModule, Validators} from "@angular/forms";
import {of} from "rxjs";

@Component({
  selector: 'app-start-chat-form',
  templateUrl: './start-chat-form.component.html',
  styleUrls: ['./start-chat-form.component.scss'],
  standalone: true,
  imports: [ReactiveFormsModule]
})
export class StartChatFormComponent implements OnInit {
    @Output() public submitted: EventEmitter<boolean> = new EventEmitter<boolean>();

    public chatForm!: FormGroup;

    public ngOnInit() {
        this.chatForm = new FormGroup({
            name: new FormControl(null, Validators.required),
            email: new FormControl(null, [Validators.required, Validators.email]),
            question: new FormControl(null, Validators.required)
        });
    }

    public submit() {
        if (this.chatForm.valid) {
            of([]).subscribe(() => {
                this.submitted.emit(true);
            });
        }
    }
}

<form [formGroup]="chatForm" (ngSubmit)="submit()" class="start-chat">
    <div class="start-chat__body">
        <input formControlName="name" class="start-chat__input" type="text" placeholder="Name"  />
        <input formControlName="email" class="start-chat__input" type="email" placeholder="Email"  />
        <textarea formControlName="question" class="start-chat__textarea" placeholder="Question" ></textarea>
    </div>
    <button type="submit" class="start-chat__btn" [disabled]="!chatForm.valid">Start Angular chat</button>
</form>
